# Generated by Django 3.2 on 2022-05-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_division', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
