# Generated by Django 3.2 on 2022-05-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventImages',
            new_name='EventImage',
        ),
        migrations.AlterModelOptions(
            name='eventimage',
            options={'verbose_name': 'Event image', 'verbose_name_plural': 'Event images'},
        ),
    ]
