# Generated by Django 3.2 on 2022-05-09 08:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdditionalInformaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('telegram_username', models.CharField(max_length=50)),
            ],
        ),
    ]
