# Generated by Django 3.2 on 2022-05-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionalinformation',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profiles/'),
        ),
    ]
