# Generated by Django 3.2 on 2022-05-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_useradditionalinformation_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionalinformation',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
